### ISSUE TITLE
Migrate Rollkit adapter to go-da

### ISSUE THREAD

**Issue by Wondertan** [thrumdev/blobs#106]
The Rollkit team has been working on the new and better DA abstraction landed at https://github.com/rollkit/go-da. The Sugondat adapter for Rollkit will have to support it soon as Rollkit [already migrated](https://github.com/rollkit/rollkit/pull/1346).

**Comment by Wondertan** [comment]
Example implementation: https://github.com/rollkit/celestia-da/blob/main/celestia.go

**Comment by rphmeier** [comment]
Thanks for the heads-up @Wondertan ! cc @pepyakin 

We'll update to the new DA abstraction shortly.

**Comment by pepyakin** [comment]
Thanks @Wondertan that makes sense! I actually first [found](https://github.com/thrumdev/blobs/issues/8) go-da but then was confused how to integrate it. After a brief look at the PR I still don't know how to do it. I would appreciate a pointer if you have handy.
