### ISSUE TITLE
disable CI for strangers

### ISSUE THREAD

**Issue by pepyakin** [thrumdev/blobs#127]
This is so that our machine doesn't get rekt by some stranger. For this there is a special button "allow CI to run". 

Hm, I am wondering though how secure is that. So you allowed CI to run for some typo fix. As soon as you do it, the adversary pushes another commit. Will the CI run again? 

- if no, then it's annoying, because some people can do several iterations. Esp. for those people we need to be more strict, since we can't expect them to do follow up.
- if yes, then the adversary can change the CI files to run their workflows and gain control over the machine.
- if yes, but only if the CI files are not changed, then it's still problematic because the adversary can take over the machine running malicious code in e.g. rust tests.

**Comment by rphmeier** [comment]
I think this is enabled. When @MrishoLukamba made an external PR I had to approve CI manually.

**Comment by MrishoLukamba** [comment]
And I will be making PRs
