### ISSUE TITLE
shim/cli/query: should it really reconnect?

### ISSUE THREAD

**Issue by pepyakin** [thrumdev/blobs#128]
there is a subcommand `query submit` that submits a blob. There are potentially others 

https://github.com/thrumdev/blobs/blob/7c2731af5805ba026a66c714db8f77922d07f3ab/sugondat-shim/src/cli.rs#L136-L139

Those commands reuse the same infra that is used for dock implementations. Therefore it will for example try to establish connection until it succeeds. 

The same would apply for `query block`. This command is useful for the same use-case as #108 (and may be even better tailored for the purpose, because it is already installed and doesn't require installing curl). The reconnection behavior is both useful and undesirable for that. 

The behavior is somewhat useful for the healthcheck when it's meant to be used as part of initial setup. I.e. any service (e.g. demo-sovereign or demo-gm) can start after `query block` finally returned a block.

At the same time, it's somewhat harmful since if it's used for health detection of a running node then it would not reconnect. You may say, well, then maybe #108 + curl is better suited for that, and you may be right. However, even for the first use-case it doesn't fit well because if the shim is not compatible with the shim it will block until the issue is fixed (= forever in a static config like docker-compose).

**Comment by rphmeier** [comment]
It's very useful for a user not to be subject to spurious failures. I suggest that the default behavior be to reconnect, and we expose a `--no-retry` flag which fails fast and can be used in health-checking.

**Comment by pepyakin** [comment]
Good call, thanks for the suggestion.
