### ISSUE TITLE
Define LenghtFeeAdjustments Parameters

### ISSUE THREAD

**Issue by gabriele-0201** [thrumdev/blobs#154]
LenghtFeeAdjustment requires 4 parameters to update `targeted_length_fee_adjustment` at the end of each block. The value is used in the following formula:

```inclusion_fee = base_fee + [targeted_length_fee_adjustment * length_fee] + [targeted_weight_fee_adjustment * weight_fee];```

It requires 4 parameters:
- Target
- AdjustmentVariable
- MinimumMultiplier
- MaximumMultiplier

The current values for `targeted_weight_fee_adjustment` are:
- TargetBlockFullness = 25%
- AdjustmentVariableBlockFullness = 75/1_000_000
- MinimumMultiplierBlockFullness = 1/10
- MaximumMultiplierBlockFullness = FixedU128::max_value()

These values are defined [here](https://research.web3.foundation/Polkadot/overview/token-economics#2-slow-adjusting-mechanism) to define `SlowAdjustingFeeUpdate`.

For `targeted_length_fee_adjustment`, the values are:
- TargetBlockSize = 16%
   - If the total block size is 5MiB, then the target block size is 0.8MiB.
- AdjustmentVariableBlockSize = 1/840
   - This value means that the maximum fee variation in one hour is 30%, following the formula `v = p / k * (1 - s*)`, where p represents the maximum fee variation percentage, k represents the period in which the variation is defined (in blocks), and s* represents the target percentage.
- MinimumMultiplierBlockSize = TODO
- MaximumMultiplierBlockSize = FixedU128::max_value()

**Comment by rphmeier** [comment]
My understanding of the `MinimumMultiplier` is that it encodes the minimum fee. We should keep this fairly low - say `1/100`. If it is set too low, it will take a long time for the fee to come back up.

**Comment by gabriele-0201** [comment]
> We should keep this fairly low - say 1/100 or 1/200  

ok, I will test some values to understand how quickly it can react and come back

> I'm also realizing now that a better fee mechanism might adjust more quickly when the average usage has been low, so fees can get extremely low but not stay suppressed by the mechanism throughout long periods of activity.

To achieve this, we can utilize multiple `AdjustmentVariable`s and keep track of the number of blocks that fall below a certain threshold. If the number of blocks exceeds a predefined amount, we can use a higher `AdjustmentVariable` to adapt more quickly to random spikes in high usage. The only downside is that it would require an additional storage item and thus an extra read and write operation in `on_finalize`. Or directly keeping track of the average AllExtrinsicaLen value and use a proportional `AdjustmentVariable`

**Comment by gabriele-0201** [comment]
Blocks per 24 hours in cumulus-node: 7200 (k)
s\* = 0.16 (TargetBlockSize)
The bound from the research in a full chain is:
v <~ (p / k(1 - s\*))
p > v \* k \* (1 - s\*)
To get p == 1, we&rsquo;d need (going from zero to target):
1 > v \* k \* (1 - s\*)
k < 1 / (v \* (1 - s\*))

k > 1000 ~ 16 mins

This should be the lower bound of the number of blocks needed
to grow from a zero multiplier to one.

The following are some tests I&rsquo;ve done to see how many blocks are needed to
grow from the min multiplier to one with the block constantly full (max block length):

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<tbody>
<tr>
<td class="org-left">Min Multiplier</td>
<td class="org-right">Blocks</td>
<td class="org-right">Hours</td>
</tr>


<tr>
<td class="org-left">1/10</td>
<td class="org-right">2302</td>
<td class="org-right">0.6</td>
</tr>


<tr>
<td class="org-left">1/100</td>
<td class="org-right">4605</td>
<td class="org-right">1.27</td>
</tr>


<tr>
<td class="org-left">1/1000</td>
<td class="org-right">6907</td>
<td class="org-right">1.91</td>
</tr>


<tr>
<td class="org-left">1/10000</td>
<td class="org-right">9210</td>
<td class="org-right">2.55</td>
</tr>
</tbody>
</table>
