### ISSUE TITLE
fees: use GenesisConfig in pallet length-fee-adjustment

### ISSUE THREAD

**Issue by gabriele-0201** [thrumdev/blobs#178]
Currently, the pallet length-fee-adjustment uses default values when empty for the storage items NextLengthMultiplier and TargetBlockSize. This is done to avoid dealing with some downsides of using GenesisConfig to define the initial values of those storage items.

The cleanest solution, however, would be to use a custom GenesisConfig in the pallet. This would make the pallet more usable for other projects as well.

Switching to this approach would likely require addressing all the necessary steps for handling a storage migration.

**Comment by MrishoLukamba** [comment]
> Currently, the pallet length-fee-adjustment uses default values when empty for the storage items NextLengthMultiplier and TargetBlockSize. This is done to avoid dealing with some downsides of using GenesisConfig to define the initial values of those storage items.
> 
> 
> 
> The cleanest solution, however, would be to use a custom GenesisConfig in the pallet. This would make the pallet more usable for other projects as well.
> 
> 
> 
> Switching to this approach would likely require addressing all the necessary steps for handling a storage migration.
> 
> 

Taking it pba student

**Comment by gabriele-0201** [comment]
Great! Thanks!

Yes, definitely! It would allow people launching a new chain to set up the initial values in the genesis config, and projects wanting to integrate it into an already running chain to make it work much more easily without the need to deal with storage
