### ISSUE TITLE
add blobs to kusama polkadotjs dashboard

### ISSUE THREAD

**Issue by muddlebee** [thrumdev/blobs#204]
https://polkadot.js.org/apps/#/explorer don't see it here 👀 

![image](https://github.com/thrumdev/blobs/assets/8139783/2a8356bf-94ee-4d36-882c-ee2d837a196a)

**Comment by rphmeier** [comment]
Will be added when & if we make a PR to Polkadot-JS to do so

(not an issue with this repository, closing)
