### ISSUE TITLE
Failed submit_blob will still end up in returned blobs

### ISSUE THREAD

**Issue by pepyakin** [thrumdev/blobs#71]
It's possible that when shim returns blobs for a specific namespace (for sovereign dock at minimum), it would attempt to create proofs of inclusion. However, some of the blobs may potentially fail to be included. Those submit blob extrinsics would still be present in the block, and as such will be returned in the resulting "blobs" field. By default the sovereign adapter would treat them as all of them included. At the same time the inclusion proof would not contain the failed blobs. Therefore, I would expect that this inclusion proof will fail verification.

This would be solved if we did not allow the invalid blobs in blocks as per #74

**Comment by rphmeier** [comment]
Can be closed now - invalid blobs now cause panics.
